
CREATE TABLE Product
(
	id INT PRIMARY KEY IDENTITY,
	name NVARCHAR(50) NULL,
	price MONEY NULL,
	quantity INT NULL,
	entryDate DATE NULL
)
SELECT * FROM Product
GO
INSERT INTO Product VALUES
('Mouse',1200.00,10,GETDATE())
GO
