//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Test_With_WinForm.SchoolServiceDB {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/WCF_App.Models")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string StudentAddressField;
        
        private string StudentIdField;
        
        private string StudentNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string StudentAddress {
            get {
                return this.StudentAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentAddressField, value) != true)) {
                    this.StudentAddressField = value;
                    this.RaisePropertyChanged("StudentAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentIdField, value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string StudentName {
            get {
                return this.StudentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentNameField, value) != true)) {
                    this.StudentNameField = value;
                    this.RaisePropertyChanged("StudentName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SchoolServiceDB.ISchoolService")]
    public interface ISchoolService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/ShowAllStudent", ReplyAction="http://tempuri.org/ISchoolService/ShowAllStudentResponse")]
        WCF_Test_With_WinForm.SchoolServiceDB.Student[] ShowAllStudent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/ShowAllStudent", ReplyAction="http://tempuri.org/ISchoolService/ShowAllStudentResponse")]
        System.Threading.Tasks.Task<WCF_Test_With_WinForm.SchoolServiceDB.Student[]> ShowAllStudentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/UpdateStudent", ReplyAction="http://tempuri.org/ISchoolService/UpdateStudentResponse")]
        void UpdateStudent(string stuId, string stuName, string stuAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/UpdateStudent", ReplyAction="http://tempuri.org/ISchoolService/UpdateStudentResponse")]
        System.Threading.Tasks.Task UpdateStudentAsync(string stuId, string stuName, string stuAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/InsertStudent", ReplyAction="http://tempuri.org/ISchoolService/InsertStudentResponse")]
        void InsertStudent(string stuId, string stuName, string stuAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/InsertStudent", ReplyAction="http://tempuri.org/ISchoolService/InsertStudentResponse")]
        System.Threading.Tasks.Task InsertStudentAsync(string stuId, string stuName, string stuAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/FindStudent", ReplyAction="http://tempuri.org/ISchoolService/FindStudentResponse")]
        WCF_Test_With_WinForm.SchoolServiceDB.Student FindStudent(string stuId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/FindStudent", ReplyAction="http://tempuri.org/ISchoolService/FindStudentResponse")]
        System.Threading.Tasks.Task<WCF_Test_With_WinForm.SchoolServiceDB.Student> FindStudentAsync(string stuId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/DeleteStudent", ReplyAction="http://tempuri.org/ISchoolService/DeleteStudentResponse")]
        void DeleteStudent(string stuId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolService/DeleteStudent", ReplyAction="http://tempuri.org/ISchoolService/DeleteStudentResponse")]
        System.Threading.Tasks.Task DeleteStudentAsync(string stuId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISchoolServiceChannel : WCF_Test_With_WinForm.SchoolServiceDB.ISchoolService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SchoolServiceClient : System.ServiceModel.ClientBase<WCF_Test_With_WinForm.SchoolServiceDB.ISchoolService>, WCF_Test_With_WinForm.SchoolServiceDB.ISchoolService {
        
        public SchoolServiceClient() {
        }
        
        public SchoolServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SchoolServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchoolServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchoolServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCF_Test_With_WinForm.SchoolServiceDB.Student[] ShowAllStudent() {
            return base.Channel.ShowAllStudent();
        }
        
        public System.Threading.Tasks.Task<WCF_Test_With_WinForm.SchoolServiceDB.Student[]> ShowAllStudentAsync() {
            return base.Channel.ShowAllStudentAsync();
        }
        
        public void UpdateStudent(string stuId, string stuName, string stuAddress) {
            base.Channel.UpdateStudent(stuId, stuName, stuAddress);
        }
        
        public System.Threading.Tasks.Task UpdateStudentAsync(string stuId, string stuName, string stuAddress) {
            return base.Channel.UpdateStudentAsync(stuId, stuName, stuAddress);
        }
        
        public void InsertStudent(string stuId, string stuName, string stuAddress) {
            base.Channel.InsertStudent(stuId, stuName, stuAddress);
        }
        
        public System.Threading.Tasks.Task InsertStudentAsync(string stuId, string stuName, string stuAddress) {
            return base.Channel.InsertStudentAsync(stuId, stuName, stuAddress);
        }
        
        public WCF_Test_With_WinForm.SchoolServiceDB.Student FindStudent(string stuId) {
            return base.Channel.FindStudent(stuId);
        }
        
        public System.Threading.Tasks.Task<WCF_Test_With_WinForm.SchoolServiceDB.Student> FindStudentAsync(string stuId) {
            return base.Channel.FindStudentAsync(stuId);
        }
        
        public void DeleteStudent(string stuId) {
            base.Channel.DeleteStudent(stuId);
        }
        
        public System.Threading.Tasks.Task DeleteStudentAsync(string stuId) {
            return base.Channel.DeleteStudentAsync(stuId);
        }
    }
}
